"""Lightweight local web panel for the Feishu research assistant.

Provides a dashboard (request volume, success rate, latency, token usage,
tool ranking), a filterable request log with detail views, and a runtime
status page. Follows the pattern of LangBot / Dify monitoring pages: summary
cards, list + lazy detail, JSON API.

Run standalone:  python web_panel.py        (default http://127.0.0.1:8090)
Optional auth:   set PANEL_TOKEN to require a token (?token=... or header).
"""

from __future__ import annotations

import html
import os
from pathlib import Path
from typing import Any

from flask import Flask, jsonify, redirect, render_template_string, request, send_from_directory
from markupsafe import Markup

from kairos.infrastructure.settings import CLAUDE_MEM_URL, DB_PATH, MODEL
from kairos.knowledge import engine as kg_engine
from kairos.memory import store as memory_store
from kairos.observability import metrics

PANEL_TOKEN = os.getenv("PANEL_TOKEN", "").strip()
PANEL_PORT = int(os.getenv("PANEL_PORT", "8090"))
PANEL_HOST = os.getenv("PANEL_HOST", "0.0.0.0")
VENDOR_DIR = Path(__file__).resolve().parent / "web_static" / "graph"


def _auth_ok() -> bool:
    if not PANEL_TOKEN:
        return True
    token = request.headers.get("X-Panel-Token", "") or request.args.get("token", "")
    return token == PANEL_TOKEN


def _pct(ok: float, total: float) -> str:
    return f"{ok / total * 100:.1f}%" if total else "-"


def _fmt_ms(value: float) -> str:
    if value >= 1000:
        return f"{value / 1000:.2f}s"
    return f"{value:.0f}ms"


LAYOUT = """<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kairós | 面板</title>
<style>
:root { --accent:#1F5A8A; --bg:#f5f6f8; --card:#fff; --text:#222; --muted:#666; --ok:#1a7f37; --err:#c62828; --border:#e3e6ea; }
* { box-sizing:border-box; }
body { margin:0; font-family:"Segoe UI","Microsoft YaHei",system-ui,sans-serif; background:var(--bg); color:var(--text); }
nav { background:var(--accent); color:#fff; padding:10px 20px; display:flex; gap:22px; align-items:center; }
nav a { color:#fff; text-decoration:none; font-weight:600; opacity:.85; }
nav a:hover, nav a.active { opacity:1; }
nav .brand { font-weight:700; margin-right:8px; }
main { max-width:1080px; margin:20px auto; padding:0 16px; }
.cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin-bottom:18px; }
.card { background:var(--card); border:1px solid var(--border); border-radius:10px; padding:14px 16px; }
.card .label { color:var(--muted); font-size:12px; }
.card .value { font-size:24px; font-weight:700; margin-top:4px; }
.card .sub { color:var(--muted); font-size:12px; margin-top:2px; }
.panel { background:var(--card); border:1px solid var(--border); border-radius:10px; padding:16px 18px; margin-bottom:18px; }
.panel h2 { margin:0 0 10px; font-size:16px; }
table { width:100%; border-collapse:collapse; font-size:13px; }
th, td { text-align:left; padding:7px 8px; border-bottom:1px solid var(--border); vertical-align:top; }
th { color:var(--muted); font-weight:600; white-space:nowrap; }
.ok { color:var(--ok); font-weight:600; }
.err { color:var(--err); font-weight:600; }
.muted { color:var(--muted); }
.tag { display:inline-block; padding:1px 8px; border-radius:10px; font-size:11px; background:#eef2f6; color:#334; }
.tool { display:inline-block; margin:2px 3px 2px 0; padding:2px 8px; border-radius:10px; font-size:11px; background:#e8f0f7; color:var(--accent); }
.bar { background:#eef2f6; border-radius:6px; height:16px; overflow:hidden; }
.bar > span { display:block; height:100%; background:var(--accent); }
.filters { display:flex; gap:10px; margin-bottom:12px; align-items:center; flex-wrap:wrap; }
.filters input, .filters select { padding:6px 10px; border:1px solid var(--border); border-radius:6px; font-size:13px; }
.btn { background:var(--accent); color:#fff; border:0; border-radius:6px; padding:6px 14px; font-size:13px; cursor:pointer; }
a { color:var(--accent); }
.detail-row { display:flex; gap:24px; margin:4px 0 10px; flex-wrap:wrap; }
.detail-item .label { color:var(--muted); font-size:12px; }
.detail-item .value { font-size:15px; font-weight:600; }
.qa { background:#fafbfc; border:1px solid var(--border); border-radius:8px; padding:12px 14px; margin:10px 0; white-space:pre-wrap; word-break:break-word; }
.pager { display:flex; gap:10px; margin-top:14px; align-items:center; }
.warn { background:#fff7e6; border:1px solid #ffe0a3; color:#7a5b00; padding:8px 12px; border-radius:8px; margin-bottom:14px; font-size:13px; }
</style>
</head>
<body>
<nav>
  <span class="brand">Kairós</span>
  <a href="/" class="active">仪表盘</a>
  <a href="/logs">请求日志</a>
  <a href="/memories">记忆</a>
  <a href="/graph">知识图谱</a>
  <a href="/health">运行状态</a>
</nav>
<main>
{{ body }}
</main>
</body>
</html>"""


def _page(body: str) -> str:
    # body is generated by us and contains trusted HTML; mark it safe so
    # Jinja2 does not escape every tag into visible source text.
    return render_template_string(LAYOUT, body=Markup(body))


def _card(label: str, value: str, sub: str = "") -> str:
    sub_html = f'<div class="sub">{html.escape(sub)}</div>' if sub else ""
    return f'<div class="card"><div class="label">{html.escape(label)}</div><div class="value">{value}</div>{sub_html}</div>'


def render_dashboard() -> str:
    s = metrics.summary()
    tools = metrics.tool_stats()
    empty_guide = ""
    if s["total"] == 0:
        empty_guide = (
            '<div class="warn">还没有请求记录。去飞书给助手发一条消息（例如「最近机器翻译有什么值得关注的进展？」），'
            "数据会自动出现在这里。</div>"
        )
    cards = "".join(
        [
            _card("总请求", f"{s['total']:,}", f"成功 {s['ok']:,} / 失败 {s['errors']:,}"),
            _card("成功率", _pct(s["ok"], s["total"]), f"今日 {s['today_count']} 次 · 失败 {s['today_errors']} 次"),
            _card("平均耗时", _fmt_ms(s["avg_latency_ms"]), "最近全部请求"),
            _card("Token 消耗", f"{s['total_tokens']:,}", "prompt + completion"),
            _card("估算成本", f"${s['estimated_cost_usd']:.2f}", "按 token × 单价估算"),
        ]
    )
    days = "".join(
        f"<td>{d['date'][5:]}<div class='bar'><span style='width:{max(2, d['count'] / max(max(x['count'] for x in s['last_7_days']), 1) * 100):.0f}%'></span></div>{d['count']}</td>"
        for d in s["last_7_days"]
    )
    tool_rows = "".join(
        f"<tr><td>{html.escape(t['tool'])}</td><td>{t['calls']}</td><td>{t['errors']}</td>"
        f"<td>{_pct(t['calls'] - t['errors'], t['calls'])}</td></tr>"
        for t in tools
    ) or "<tr><td colspan='4' class='muted'>暂无工具调用记录</td></tr>"
    failed_rows, _ = metrics.list_logs(page=1, page_size=5, status="error")
    if failed_rows:
        fail_rows_html = "".join(
            "<tr>"
            f"<td class='muted'>{html.escape(r['created_at'])}</td>"
            f"<td>{html.escape(r['question'][:50])}</td>"
            f"<td>{html.escape(r['error_type']) or '未知'}</td>"
            f"<td><a href='/logs/{r['id']}'>详情</a></td>"
            "</tr>"
            for r in failed_rows
        )
        recent_fail = (
            "<div class='panel'><h2>最近失败</h2><table>"
            "<tr><th>时间</th><th>问题</th><th>错误类型</th><th></th></tr>"
            f"{fail_rows_html}</table></div>"
        )
    else:
        recent_fail = ""
    body = f"""
    {empty_guide}
    <div class="cards">{cards}</div>
    <div class="panel"><h2>近 7 天请求量</h2><table><tr>{days}</tr></table></div>
    <div class="panel"><h2>工具调用排行</h2><table><tr><th>工具</th><th>调用</th><th>失败</th><th>成功率</th></tr>{tool_rows}</table></div>
    {recent_fail}
    """
    return _page(body)


def render_logs() -> str:
    page = max(1, int(request.args.get("page", "1") or 1))
    status = request.args.get("status", "")
    tool = request.args.get("tool", "").strip()
    rows, total = metrics.list_logs(page=page, status=status, tool=tool)
    total_pages = max(1, (total + 19) // 20)
    rows_html = ""
    for r in rows:
        state = "ok" if r["status"] == "ok" else "err"
        tools_html = "".join(f'<span class="tool">{html.escape(t)}</span>' for t in r["tool_sequence"][:6]) or '<span class="muted">—</span>'
        rows_html += (
            "<tr>"
            f"<td class='muted'>{html.escape(r['created_at'])}</td>"
            f"<td>{html.escape(r['question'][:60])}</td>"
            f"<td>{len(r['tool_sequence'])}</td>"
            f"<td>{_fmt_ms(r['latency_ms'])}</td>"
            f"<td>{r['total_tokens']}</td>"
            f"<td class='{state}'>{'成功' if r['status']=='ok' else '失败'}</td>"
            f"<td><a href='/logs/{r['id']}'>详情</a></td>"
            "</tr>"
        )
    pager = (
        f"<div class='pager'><a class='btn' href='/logs?page={page-1}&status={status}&tool={tool}'>上一页</a>"
        f"<span class='muted'>第 {page} / {total_pages} 页 · 共 {total} 条</span>"
        f"<a class='btn' href='/logs?page={page+1}&status={status}&tool={tool}'>下一页</a></div>"
    )
    body = f"""
    <div class="panel">
      <h2>请求日志</h2>
      <form class="filters" method="get">
        <select name="status">
          <option value="">全部状态</option>
          <option value="ok" {'selected' if status=='ok' else ''}>成功</option>
          <option value="error" {'selected' if status=='error' else ''}>失败</option>
        </select>
        <input name="tool" placeholder="按工具名过滤，如 web_search" value="{html.escape(tool)}">
        <button class="btn" type="submit">筛选</button>
      </form>
      <table><tr><th>时间</th><th>问题</th><th>工具数</th><th>耗时</th><th>Token</th><th>状态</th><th></th></tr>{rows_html}</table>
      {pager}
    </div>
    """
    return _page(body)


def render_log_detail(log_id: int) -> str:
    r = metrics.get_log(log_id)
    if not r:
        return _page("<div class='panel'><h2>未找到该日志</h2><p><a href='/logs'>返回列表</a></p></div>")
    state = "ok" if r["status"] == "ok" else "err"
    steps = "".join(
        f"<div>{i + 1}. <span class='tool'>{html.escape(t)}</span></div>" for i, t in enumerate(r["tool_sequence"])
    ) or '<span class="muted">未调用工具</span>'
    body = f"""
    <div class="panel">
      <h2>请求详情 #{r['id']}</h2>
      <div class="detail-row">
        <div class="detail-item"><div class="label">时间</div><div class="value">{html.escape(r['created_at'])}</div></div>
        <div class="detail-item"><div class="label">状态</div><div class="value {state}">{'成功' if r['status']=='ok' else '失败'}</div></div>
        <div class="detail-item"><div class="label">耗时</div><div class="value">{_fmt_ms(r['latency_ms'])}</div></div>
        <div class="detail-item"><div class="label">Token</div><div class="value">{r['total_tokens']}（prompt {r['prompt_tokens']} / completion {r['completion_tokens']}）</div></div>
        <div class="detail-item"><div class="label">上下文长度</div><div class="value">{r['context_len']} 字符</div></div>
        <div class="detail-item"><div class="label">请求 ID</div><div class="value muted">{html.escape(r['request_id'])}</div></div>
      </div>
      <h3 class="muted">问题</h3>
      <div class="qa">{html.escape(r['question'])}</div>
      <h3 class="muted">工具调用链</h3>
      {steps}
      <h3 class="muted">回答</h3>
      <div class="qa">{html.escape(r['answer']) or "<span class='muted'>（无回答）</span>"}</div>
      {"<div class='warn'>错误类型：" + html.escape(r['error_type']) + "</div>" if r['status'] != "ok" else ""}
      <p><a href="/logs">&lt;- 返回日志列表</a></p>
    </div>
    """
    return _page(body)


def render_health() -> str:
    from kairos.infrastructure.settings import PROJECT_ROOT

    try:
        from kairos.agent.runtime import NATIVE_TOOLS

        tool_count = len(NATIVE_TOOLS)
    except Exception:
        tool_count = "未知（未配置 DEEPSEEK_API_KEY 时无法加载）"
    rows = [
        ("模型", MODEL),
        ("注册工具数", str(tool_count)),
        ("Claude-Mem 长期记忆", "已配置" if CLAUDE_MEM_URL else "未配置（可选）"),
        ("SQLite 数据库", str(DB_PATH)),
        ("项目根目录", str(PROJECT_ROOT)),
        ("面板认证", "PANEL_TOKEN 已启用" if PANEL_TOKEN else "未设置 PANEL_TOKEN（仅建议本机使用）"),
        ("面板端口", str(PANEL_PORT)),
    ]
    rows_html = "".join(f"<tr><td>{html.escape(k)}</td><td>{html.escape(str(v))}</td></tr>" for k, v in rows)
    body = f"""
    <div class="panel"><h2>运行状态</h2><table>{rows_html}</table></div>
    <div class="panel"><h2>说明</h2><p class="muted">本面板为本地运维工具，数据来自请求日志（question/answer 已脱敏，owner 已哈希）。</p></div>
    """
    return _page(body)


def render_memories() -> str:
    stats = memory_store.count_memories()
    rows = memory_store.list_all_memories(limit=300)
    by_owner: dict[str, list[dict]] = {}
    for row in rows:
        by_owner.setdefault(row["owner_id"], []).append(row)
    cards = "".join(
        [
            _card("记忆总数", f"{stats['total']}", f"核心 {stats['core']} / 存档 {stats['archive']}"),
            _card("记忆用户", f"{stats['owners']}", "按用户隔离"),
        ]
    )
    if not rows:
        body = f"""
        {cards}
        <div class="panel"><h2>记忆列表</h2><p class="muted">还没有记忆。去飞书和助手聊天，助手会自动提取并保存长期记忆。</p></div>
        """
        return _page(body)
    sections = []
    for owner, owner_rows in by_owner.items():
        owner_rows.sort(key=lambda r: (not r["is_core"], r["updated_at"]), reverse=True)
        rows_html = ""
        for r in owner_rows:
            tag = "核心" if r["is_core"] else "存档"
            rows_html += (
                "<tr>"
                f"<td><span class='tag'>{tag}</span></td>"
                f"<td>{html.escape(r['category'])}</td>"
                f"<td>{html.escape(r['content'])}</td>"
                f"<td>{r['access_count']}</td>"
                f"<td class='muted'>{html.escape(r['updated_at'])}</td>"
                "<td><form method='post' action='/api/memories/delete' "
                f"onsubmit='return confirm(\"删除这条记忆？\")'>"
                f"<input type='hidden' name='memory_id' value='{html.escape(r['memory_id'])}'>"
                "<button class='btn' type='submit'>删除</button></form></td>"
                "</tr>"
            )
        sections.append(
            "<div class='panel'>"
            f"<h2>用户 {html.escape(owner)} <span class='muted'>({len(owner_rows)} 条)</span></h2>"
            "<table><tr><th>层级</th><th>类别</th><th>内容</th><th>访问</th><th>更新时间</th><th></th></tr>"
            f"{rows_html}</table>"
            f"<form method='post' action='/api/memories/clear' style='margin-top:8px' "
            f"onsubmit='return confirm(\"清空该用户全部记忆？\")'>"
            f"<input type='hidden' name='owner_id' value='{html.escape(owner)}'>"
            "<button class='btn' type='submit'>清空该用户记忆</button></form>"
            "</div>"
        )
    body = f"""
    <div class="cards">{cards}</div>
    {''.join(sections)}
    """
    return _page(body)


def render_graph() -> str:
    """Interactive knowledge graph view — sigma.js WebGL renderer.

    The legacy canvas version recomputed O(n^2) repulsion on the main thread
    every frame and froze past ~1k nodes. This build renders with WebGL
    (sigma.js v2) and lays out with ForceAtlas2 running in a web worker
    (Barnes-Hut, O(n log n)), keeping thousands of entities fluid.
    """
    body = """
    <style>
      .graph-toolbar { display:flex; gap:10px; align-items:center; margin-bottom:12px; flex-wrap:wrap; }
      .graph-toolbar input { padding:6px 10px; border:1px solid var(--border); border-radius:6px; font-size:13px; width:220px; }
      .graph-toolbar button { padding:6px 12px; }
      #graph-wrap { position:relative; height:72vh; border:1px solid var(--border); border-radius:10px; background:#fbfcfe; overflow:hidden; }
      #graph-empty { position:absolute; inset:0; display:none; align-items:center; justify-content:center; text-align:center; padding:20px; z-index:4; background:#fbfcfe; }
      #graph-search-list { position:absolute; top:52px; left:12px; z-index:6; background:#fff; border:1px solid var(--border);
        border-radius:8px; box-shadow:0 6px 24px rgba(15,25,40,.12); display:none; min-width:240px; max-height:280px; overflow:auto; }
      #graph-search-list .s-item { padding:7px 12px; font-size:13px; cursor:pointer; display:flex; gap:8px; align-items:center; }
      #graph-search-list .s-item:hover { background:#f0f4fa; }
      #graph-search-list .s-item .deg { color:var(--muted); font-size:11px; margin-left:auto; }
      .graph-legend { display:flex; gap:14px; flex-wrap:wrap; margin-top:10px; }
      .legend-item { display:inline-flex; align-items:center; gap:6px; font-size:12px; color:var(--muted); cursor:pointer;
        user-select:none; padding:2px 6px; border-radius:6px; }
      .legend-item:hover { background:#eef2f8; }
      .legend-item.off { opacity:.35; text-decoration:line-through; }
      .legend-dot { width:10px; height:10px; border-radius:50%; display:inline-block; }
      .graph-detail { margin-top:12px; padding:12px 14px; background:#fafbfc; border:1px solid var(--border); border-radius:8px; font-size:13px; min-height:20px; max-height:34vh; overflow:auto; }
      .graph-detail .detail-title { font-size:14px; margin-bottom:8px; display:flex; align-items:center; gap:8px; flex-wrap:wrap; }
      .graph-detail .rel { padding:3px 0; border-bottom:1px dashed var(--border); cursor:pointer; }
      .graph-detail .rel:hover { background:#f0f4fa; }
      .graph-detail .rel .pred { color:var(--accent); font-weight:600; margin-right:6px; }
      #layout-status { font-size:12px; color:var(--muted); }
    </style>
    <div class="cards">
      <div class="card"><div class="label">文档</div><div class="value" id="stat-docs">—</div></div>
      <div class="card"><div class="label">实体</div><div class="value" id="stat-entities">—</div></div>
      <div class="card"><div class="label">关系</div><div class="value" id="stat-relations">—</div></div>
    </div>
    <div class="panel">
      <div class="graph-toolbar">
        <input id="graph-search" placeholder="搜索实体并定位…" autocomplete="off">
        <button class="btn" id="btn-layout" type="button">暂停布局</button>
        <button class="btn" id="btn-reheat" type="button">重新布局</button>
        <button class="btn" id="btn-reset" type="button">重置视图</button>
        <span id="layout-status"></span>
        <span class="muted">滚轮缩放 · 拖拽平移 · 拖节点调整 · 点击查看关联</span>
      </div>
      <div id="graph-wrap">
        <div id="graph-empty" class="warn"></div>
        <div id="graph-search-list"></div>
      </div>
      <div class="graph-legend" id="graph-legend"></div>
      <div class="graph-detail" id="graph-detail"><span class="muted">点击节点查看关联关系</span></div>
    </div>
    <script src="/graph/vendor/graphology.umd.min.js"></script>
    <script src="/graph/vendor/fa2.min.js"></script>
    <script src="/graph/vendor/fa2.supervisor.min.js"></script>
    <script src="/graph/vendor/sigma.min.js"></script>
    <script>
    (function(){
      function esc(s){ return String(s).replace(/[&<>"']/g, function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
      var wrap = document.getElementById('graph-wrap');
      var empty = document.getElementById('graph-empty');
      var detail = document.getElementById('graph-detail');
      var legendEl = document.getElementById('graph-legend');
      var statusEl = document.getElementById('layout-status');

      fetch('/api/graph').then(function(r){ return r.json(); }).then(function(data){
        document.getElementById('stat-docs').textContent = data.stats.documents;
        document.getElementById('stat-entities').textContent = data.stats.entities;
        document.getElementById('stat-relations').textContent = data.stats.relations;
        if (!data.nodes || !data.nodes.length){
          empty.textContent = '知识图谱还是空的。';
          empty.style.display = 'flex';
          return;
        }
        init(data.nodes, data.edges);
      }).catch(function(e){
        empty.textContent = '加载图谱失败：' + esc(e && e.message ? e.message : '');
        empty.style.display = 'flex';
      });

      function init(rawNodes, rawEdges){
        var PALETTE = ['#1f77b4','#ff7f0e','#2ca02c','#d62728','#9467bd','#8c564b','#e377c2','#7f7f7f','#bcbd22','#17becf'];
        var typeColor = {}, paletteIdx = 0;

        var graph = new graphology.Graph({ multi: false, type: 'undirected' });
        rawNodes.forEach(function(n){
          if (!typeColor[n.type]) typeColor[n.type] = PALETTE[paletteIdx++ % PALETTE.length];
          var angle = Math.random() * Math.PI * 2, r = 80 * Math.sqrt(Math.random());
          try {
            graph.addNode(String(n.id), {
              label: n.name, name: n.name, etype: n.type, degree: n.degree || 0,
              x: Math.cos(angle) * r, y: Math.sin(angle) * r, size: 3
            });
          } catch (err) { /* duplicate id */ }
        });
        rawEdges.forEach(function(e){
          var s = String(e.source), t = String(e.target);
          if (graph.hasNode(s) && graph.hasNode(t) && s !== t && !graph.hasEdge(s, t)){
            try { graph.addEdge(s, t, { predicate: e.predicate, color: 'rgba(150,165,180,.35)', size: 1 }); } catch (err) {}
          }
        });

        // size by degree (sqrt scaling)
        graph.forEachNode(function(node, attrs){
          graph.setNodeAttribute(node, 'size', Math.max(3.5, Math.min(26, 3 + Math.sqrt(attrs.degree) * 2.2)));
        });

        // ---- layout: FA2 supervisor keeps matrices resident in a worker ----
        var order = graph.order;
        var settings = Object.assign(
          graphologyLayoutForceAtlas2.inferSettings(order),
          { barnesHutTheta: 0.9, scalingRatio: 6, slowDown: Math.max(4, 1 + Math.log(order)) }
        );
        statusEl.textContent = '初始布局中…（' + order + ' 节点）';
        // synchronous warm-up so the first paint is already structured
        graphologyLayoutForceAtlas2.assign(graph, {
          iterations: order > 4000 ? 60 : 120,
          settings: settings
        });

        var renderer = new Sigma(graph, wrap, {
          allowInvalidContainer: true,
          renderEdgeLabels: false,
          labelRenderedSizeThreshold: 13,
          labelDensity: 1.1,
          minCameraRatio: 0.02,
          maxCameraRatio: 12
        });

        // ---- interaction state ----
        var hoveredNode = null, selectedNode = null, searchHit = null;
        var offTypes = {};
        var nbSet = {};

        renderer.on('enterNode', function(e){ hoveredNode = e.node; nbSet = neighborsOf(e.node); refresh(); });
        renderer.on('leaveNode', function(){ hoveredNode = null; nbSet = selectedNode ? neighborsOf(selectedNode) : {}; refresh(); });
        renderer.on('clickNode', function(e){ selectNode(e.node); });
        renderer.on('clickStage', function(){
          if (selectedNode){ selectedNode = null; nbSet = {}; renderDetail(null); refresh(); }
        });
        renderer.on('downNode', function(){ setRunning(false); });   // dragging pauses layout for precision

        function neighborsOf(node){
          var set = {};
          graph.forEachNeighbor(node, function(nb){ set[nb] = true; });
          return set;
        }

        // ---- reducers (light table lookups; memoized by sigma) ----
        renderer.setSetting('nodeReducer', function(node, data){
          var res = Object.assign({}, data);
          res.color = typeColor[data.etype] || '#999';
          if (offTypes[data.etype]) { res.hidden = true; return res; }
          var active = hoveredNode || selectedNode || searchHit;
          if (active){
            if (node === active){ res.highlighted = true; res.zIndex = 3; res.size = data.size * 1.2; }
            else if (nbSet[node]){ res.zIndex = 2; }
            else {
              res.color = 'rgba(160,170,185,.22)';
              res.label = null;
              res.size = 2.5;
            }
          }
          if (searchHit === node && node !== active){ res.highlighted = true; }
          return res;
        });
        renderer.setSetting('edgeReducer', function(edge, data){
          var res = Object.assign({}, data);
          var active = hoveredNode || selectedNode;
          if (active){
            var s = graph.source(edge), t = graph.target(edge);
            if (s !== active && t !== active) res.hidden = true;
            else { res.color = '#5a7699'; res.size = 1.6; }
          } else {
            res.color = 'rgba(150,165,180,.35)';
            res.size = 1;
          }
          return res;
        });

        // ---- worker-driven layout ----
        var layout = new graphologyLayoutForceAtlas2Supervisor(graph, { settings: settings });

        var refreshQueued = false;
        function refresh(){
          if (!refreshQueued){
            refreshQueued = true;
            requestAnimationFrame(function(){ refreshQueued = false; renderer.refresh(); });
          }
        }
        // repaint loop only while the worker is feeding new positions
        (function paintLoop(){
          if (layout.isRunning()) renderer.refresh();
          requestAnimationFrame(paintLoop);
        })();

        function setRunning(v){
          if (v && !layout.isRunning()){ layout.start(); }
          else if (!v && layout.isRunning()){ layout.stop(); renderer.refresh(); }
          document.getElementById('btn-layout').textContent = v ? '暂停布局' : '继续布局';
          statusEl.textContent = v ? '布局运行中（worker 线程）' : '布局已暂停';
        }

        document.getElementById('btn-layout').addEventListener('click', function(){ setRunning(!layout.isRunning()); });
        document.getElementById('btn-reheat').addEventListener('click', function(){
          layout.stop();
          statusEl.textContent = '重新布局…';
          graphologyLayoutForceAtlas2.assign(graph, { iterations: 150, settings: settings });
          renderer.refresh();
          layout.start();
        });
        document.getElementById('btn-reset').addEventListener('click', function(){
          renderer.getCamera().animate({ x: 0, y: 0, ratio: 1, angle: 0 }, { duration: 300 });
        });

        // ---- legend with type filtering ----
        legendEl.innerHTML = Object.keys(typeColor).map(function(t){
          return '<span class="legend-item" data-type="' + esc(t) + '">' +
                 '<span class="legend-dot" style="background:' + typeColor[t] + '"></span>' + esc(t) + '</span>';
        }).join('');
        legendEl.addEventListener('click', function(ev){
          var item = ev.target.closest('.legend-item');
          if (!item) return;
          var t = item.getAttribute('data-type');
          offTypes[t] = !offTypes[t];
          item.classList.toggle('off', !!offTypes[t]);
          refresh();
        });

        // ---- detail panel ----
        function renderDetail(node){
          if (!node){
            detail.innerHTML = '<span class="muted">点击节点查看关联关系</span>';
            return;
          }
          var attrs = graph.getNodeAttributes(node);
          var rows = [];
          graph.forEachEdge(node, function(edge, eAttrs, s, t){
            var other = s === node ? t : s;
            rows.push('<div class="rel" data-node="' + esc(other) + '">' +
              '<span class="pred">' + esc(eAttrs.predicate || '相关') + '</span>' +
              esc(graph.getNodeAttribute(other, 'name')) +
              ' <span style="color:var(--muted)">(' + esc(graph.getNodeAttribute(other, 'etype')) + ')</span></div>');
          });
          detail.innerHTML =
            '<div class="detail-title"><strong>' + esc(attrs.name) + '</strong>' +
            '<span class="tag">' + esc(attrs.etype) + '</span>' +
            '<span class="muted">度数 ' + attrs.degree + '</span></div>' +
            (rows.length ? rows.join('') : '<span class="muted">无关联关系</span>');
        }
        detail.addEventListener('click', function(ev){
          var rel = ev.target.closest('.rel');
          if (!rel) return;
          focusNode(rel.getAttribute('data-node'));
        });

        function selectNode(node){
          selectedNode = node;
          nbSet = neighborsOf(node);
          renderDetail(node);
          var pos = renderer.getNodeDisplayData(node);
          if (pos){
            renderer.getCamera().animate(
              { x: pos.x, y: pos.y, ratio: Math.max(0.08, renderer.getCamera().getState().ratio * 0.55) },
              { duration: 320 }
            );
          }
          refresh();
        }
        function focusNode(node){
          if (!graph.hasNode(node)) return;
          selectNode(node);
        }

        // ---- search ----
        var input = document.getElementById('graph-search');
        var listEl = document.getElementById('graph-search-list');
        input.addEventListener('input', function(){
          var q = input.value.trim().toLowerCase();
          if (!q){ listEl.style.display = 'none'; searchHit = null; refresh(); return; }
          var hits = [];
          graph.forEachNode(function(node, attrs){
            if (hits.length >= 12) return;
            if (offTypes[attrs.etype]) return;
            if (attrs.name.toLowerCase().indexOf(q) !== -1) hits.push(node);
          });
          listEl.innerHTML = hits.map(function(node){
            var a = graph.getNodeAttributes(node);
            return '<div class="s-item" data-node="' + node + '">' +
                   '<span class="legend-dot" style="background:' + (typeColor[a.etype] || '#999') + '"></span>' +
                   esc(a.name) + '<span class="deg">度 ' + a.degree + '</span></div>';
          }).join('');
          listEl.style.display = hits.length ? 'block' : 'none';
        });
        listEl.addEventListener('click', function(ev){
          var item = ev.target.closest('.s-item');
          if (!item) return;
          listEl.style.display = 'none';
          input.value = '';
          selectNode(item.getAttribute('data-node'));
        });

        layout.start();
        statusEl.textContent = '布局运行中（worker 线程）· 可随时暂停';
      }
    })();
    </script>
    """
    return _page(body)


def create_app() -> Flask:
    app = Flask(__name__)
    app.json.ensure_ascii = False

    @app.before_request
    def require_token() -> Any:
        if not _auth_ok():
            return jsonify({"error": "unauthorized", "hint": "set PANEL_TOKEN or pass ?token="}), 401
        return None

    @app.get("/")
    def dashboard() -> str:
        return render_dashboard()

    @app.get("/logs")
    def logs() -> str:
        return render_logs()

    @app.get("/logs/<int:log_id>")
    def log_detail(log_id: int) -> str:
        return render_log_detail(log_id)

    @app.get("/health")
    def health() -> str:
        return render_health()

    @app.get("/memories")
    def memories() -> str:
        return render_memories()

    @app.get("/graph")
    def graph() -> str:
        return render_graph()

    @app.get("/graph/vendor/<path:fname>")
    def graph_vendor(fname: str):
        resp = send_from_directory(VENDOR_DIR, fname)
        resp.headers["Cache-Control"] = "public, max-age=604800"
        return resp

    @app.get("/api/graph")
    def api_graph() -> Any:
        try:
            kg_engine.init()
            return jsonify(kg_engine.export_graph())
        except Exception as exc:  # noqa: BLE001
            return jsonify({"error": str(exc)}), 500

    @app.post("/api/memories/delete")
    def api_memory_delete() -> Any:
        memory_id = request.form.get("memory_id", "")
        if memory_id and memory_store.delete_memory(memory_id):
            return redirect("/memories")
        return "未找到该记忆", 404

    @app.post("/api/memories/clear")
    def api_memory_clear() -> Any:
        owner_id = request.form.get("owner_id", "")
        if owner_id:
            memory_store.forget_memories(owner_id)
        return redirect("/memories")

    @app.get("/api/summary")
    def api_summary() -> Any:
        return jsonify(metrics.summary())

    @app.get("/api/logs")
    def api_logs() -> Any:
        page = max(1, int(request.args.get("page", "1") or 1))
        status = request.args.get("status", "")
        tool = request.args.get("tool", "").strip()
        rows, total = metrics.list_logs(page=page, status=status, tool=tool)
        return jsonify({"total": total, "page": page, "rows": rows})

    @app.get("/api/logs/<int:log_id>")
    def api_log_detail(log_id: int) -> Any:
        row = metrics.get_log(log_id)
        return (jsonify(row), 200) if row else (jsonify({"error": "not found"}), 404)

    @app.get("/api/tools")
    def api_tools() -> Any:
        return jsonify(metrics.tool_stats())

    return app


def main() -> None:
    metrics.init_metrics_table()
    memory_store.init_db()
    app = create_app()
    print(f"web panel listening on {PANEL_HOST}:{PANEL_PORT}" + (" (PANEL_TOKEN required)" if PANEL_TOKEN else ""))
    app.run(host=PANEL_HOST, port=PANEL_PORT, debug=False, use_reloader=False)


if __name__ == "__main__":
    main()
