"""Lightweight local web panel for the Feishu research assistant.

Provides a dashboard (request volume, success rate, latency, token usage,
tool ranking), a filterable request log with detail views, and a runtime
status page. Follows the pattern of LangBot / Dify monitoring pages: summary
cards, list + lazy detail, JSON API.

Run standalone:  python web_panel.py        (default http://127.0.0.1:8090)
Optional auth:   set PANEL_TOKEN to require a token (?token=... or header).
"""

from __future__ import annotations

import html
import os
from typing import Any

from flask import Flask, jsonify, redirect, render_template_string, request
from markupsafe import Markup

from kairos.infrastructure.settings import CLAUDE_MEM_URL, DB_PATH, MODEL
from kairos.knowledge import engine as kg_engine
from kairos.memory import store as memory_store
from kairos.observability import metrics

PANEL_TOKEN = os.getenv("PANEL_TOKEN", "").strip()
PANEL_PORT = int(os.getenv("PANEL_PORT", "8090"))
PANEL_HOST = os.getenv("PANEL_HOST", "0.0.0.0")


def _auth_ok() -> bool:
    if not PANEL_TOKEN:
        return True
    token = request.headers.get("X-Panel-Token", "") or request.args.get("token", "")
    return token == PANEL_TOKEN


def _pct(ok: float, total: float) -> str:
    return f"{ok / total * 100:.1f}%" if total else "-"


def _fmt_ms(value: float) -> str:
    if value >= 1000:
        return f"{value / 1000:.2f}s"
    return f"{value:.0f}ms"


LAYOUT = """<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kairós | 面板</title>
<style>
:root { --accent:#1F5A8A; --bg:#f5f6f8; --card:#fff; --text:#222; --muted:#666; --ok:#1a7f37; --err:#c62828; --border:#e3e6ea; }
* { box-sizing:border-box; }
body { margin:0; font-family:"Segoe UI","Microsoft YaHei",system-ui,sans-serif; background:var(--bg); color:var(--text); }
nav { background:var(--accent); color:#fff; padding:10px 20px; display:flex; gap:22px; align-items:center; }
nav a { color:#fff; text-decoration:none; font-weight:600; opacity:.85; }
nav a:hover, nav a.active { opacity:1; }
nav .brand { font-weight:700; margin-right:8px; }
main { max-width:1080px; margin:20px auto; padding:0 16px; }
.cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin-bottom:18px; }
.card { background:var(--card); border:1px solid var(--border); border-radius:10px; padding:14px 16px; }
.card .label { color:var(--muted); font-size:12px; }
.card .value { font-size:24px; font-weight:700; margin-top:4px; }
.card .sub { color:var(--muted); font-size:12px; margin-top:2px; }
.panel { background:var(--card); border:1px solid var(--border); border-radius:10px; padding:16px 18px; margin-bottom:18px; }
.panel h2 { margin:0 0 10px; font-size:16px; }
table { width:100%; border-collapse:collapse; font-size:13px; }
th, td { text-align:left; padding:7px 8px; border-bottom:1px solid var(--border); vertical-align:top; }
th { color:var(--muted); font-weight:600; white-space:nowrap; }
.ok { color:var(--ok); font-weight:600; }
.err { color:var(--err); font-weight:600; }
.muted { color:var(--muted); }
.tag { display:inline-block; padding:1px 8px; border-radius:10px; font-size:11px; background:#eef2f6; color:#334; }
.tool { display:inline-block; margin:2px 3px 2px 0; padding:2px 8px; border-radius:10px; font-size:11px; background:#e8f0f7; color:var(--accent); }
.bar { background:#eef2f6; border-radius:6px; height:16px; overflow:hidden; }
.bar > span { display:block; height:100%; background:var(--accent); }
.filters { display:flex; gap:10px; margin-bottom:12px; align-items:center; flex-wrap:wrap; }
.filters input, .filters select { padding:6px 10px; border:1px solid var(--border); border-radius:6px; font-size:13px; }
.btn { background:var(--accent); color:#fff; border:0; border-radius:6px; padding:6px 14px; font-size:13px; cursor:pointer; }
a { color:var(--accent); }
.detail-row { display:flex; gap:24px; margin:4px 0 10px; flex-wrap:wrap; }
.detail-item .label { color:var(--muted); font-size:12px; }
.detail-item .value { font-size:15px; font-weight:600; }
.qa { background:#fafbfc; border:1px solid var(--border); border-radius:8px; padding:12px 14px; margin:10px 0; white-space:pre-wrap; word-break:break-word; }
.pager { display:flex; gap:10px; margin-top:14px; align-items:center; }
.warn { background:#fff7e6; border:1px solid #ffe0a3; color:#7a5b00; padding:8px 12px; border-radius:8px; margin-bottom:14px; font-size:13px; }
</style>
</head>
<body>
<nav>
  <span class="brand">Kairós</span>
  <a href="/" class="active">仪表盘</a>
  <a href="/logs">请求日志</a>
  <a href="/memories">记忆</a>
  <a href="/graph">知识图谱</a>
  <a href="/health">运行状态</a>
</nav>
<main>
{{ body }}
</main>
</body>
</html>"""


def _page(body: str) -> str:
    # body is generated by us and contains trusted HTML; mark it safe so
    # Jinja2 does not escape every tag into visible source text.
    return render_template_string(LAYOUT, body=Markup(body))


def _card(label: str, value: str, sub: str = "") -> str:
    sub_html = f'<div class="sub">{html.escape(sub)}</div>' if sub else ""
    return f'<div class="card"><div class="label">{html.escape(label)}</div><div class="value">{value}</div>{sub_html}</div>'


def render_dashboard() -> str:
    s = metrics.summary()
    tools = metrics.tool_stats()
    empty_guide = ""
    if s["total"] == 0:
        empty_guide = (
            '<div class="warn">还没有请求记录。去飞书给助手发一条消息（例如「最近机器翻译有什么值得关注的进展？」），'
            "数据会自动出现在这里。</div>"
        )
    cards = "".join(
        [
            _card("总请求", f"{s['total']:,}", f"成功 {s['ok']:,} / 失败 {s['errors']:,}"),
            _card("成功率", _pct(s["ok"], s["total"]), f"今日 {s['today_count']} 次 · 失败 {s['today_errors']} 次"),
            _card("平均耗时", _fmt_ms(s["avg_latency_ms"]), "最近全部请求"),
            _card("Token 消耗", f"{s['total_tokens']:,}", "prompt + completion"),
            _card("估算成本", f"${s['estimated_cost_usd']:.2f}", "按 token × 单价估算"),
        ]
    )
    days = "".join(
        f"<td>{d['date'][5:]}<div class='bar'><span style='width:{max(2, d['count'] / max(max(x['count'] for x in s['last_7_days']), 1) * 100):.0f}%'></span></div>{d['count']}</td>"
        for d in s["last_7_days"]
    )
    tool_rows = "".join(
        f"<tr><td>{html.escape(t['tool'])}</td><td>{t['calls']}</td><td>{t['errors']}</td>"
        f"<td>{_pct(t['calls'] - t['errors'], t['calls'])}</td></tr>"
        for t in tools
    ) or "<tr><td colspan='4' class='muted'>暂无工具调用记录</td></tr>"
    failed_rows, _ = metrics.list_logs(page=1, page_size=5, status="error")
    if failed_rows:
        fail_rows_html = "".join(
            "<tr>"
            f"<td class='muted'>{html.escape(r['created_at'])}</td>"
            f"<td>{html.escape(r['question'][:50])}</td>"
            f"<td>{html.escape(r['error_type']) or '未知'}</td>"
            f"<td><a href='/logs/{r['id']}'>详情</a></td>"
            "</tr>"
            for r in failed_rows
        )
        recent_fail = (
            "<div class='panel'><h2>最近失败</h2><table>"
            "<tr><th>时间</th><th>问题</th><th>错误类型</th><th></th></tr>"
            f"{fail_rows_html}</table></div>"
        )
    else:
        recent_fail = ""
    body = f"""
    {empty_guide}
    <div class="cards">{cards}</div>
    <div class="panel"><h2>近 7 天请求量</h2><table><tr>{days}</tr></table></div>
    <div class="panel"><h2>工具调用排行</h2><table><tr><th>工具</th><th>调用</th><th>失败</th><th>成功率</th></tr>{tool_rows}</table></div>
    {recent_fail}
    """
    return _page(body)


def render_logs() -> str:
    page = max(1, int(request.args.get("page", "1") or 1))
    status = request.args.get("status", "")
    tool = request.args.get("tool", "").strip()
    rows, total = metrics.list_logs(page=page, status=status, tool=tool)
    total_pages = max(1, (total + 19) // 20)
    rows_html = ""
    for r in rows:
        state = "ok" if r["status"] == "ok" else "err"
        tools_html = "".join(f'<span class="tool">{html.escape(t)}</span>' for t in r["tool_sequence"][:6]) or '<span class="muted">—</span>'
        rows_html += (
            "<tr>"
            f"<td class='muted'>{html.escape(r['created_at'])}</td>"
            f"<td>{html.escape(r['question'][:60])}</td>"
            f"<td>{len(r['tool_sequence'])}</td>"
            f"<td>{_fmt_ms(r['latency_ms'])}</td>"
            f"<td>{r['total_tokens']}</td>"
            f"<td class='{state}'>{'成功' if r['status']=='ok' else '失败'}</td>"
            f"<td><a href='/logs/{r['id']}'>详情</a></td>"
            "</tr>"
        )
    pager = (
        f"<div class='pager'><a class='btn' href='/logs?page={page-1}&status={status}&tool={tool}'>上一页</a>"
        f"<span class='muted'>第 {page} / {total_pages} 页 · 共 {total} 条</span>"
        f"<a class='btn' href='/logs?page={page+1}&status={status}&tool={tool}'>下一页</a></div>"
    )
    body = f"""
    <div class="panel">
      <h2>请求日志</h2>
      <form class="filters" method="get">
        <select name="status">
          <option value="">全部状态</option>
          <option value="ok" {'selected' if status=='ok' else ''}>成功</option>
          <option value="error" {'selected' if status=='error' else ''}>失败</option>
        </select>
        <input name="tool" placeholder="按工具名过滤，如 web_search" value="{html.escape(tool)}">
        <button class="btn" type="submit">筛选</button>
      </form>
      <table><tr><th>时间</th><th>问题</th><th>工具数</th><th>耗时</th><th>Token</th><th>状态</th><th></th></tr>{rows_html}</table>
      {pager}
    </div>
    """
    return _page(body)


def render_log_detail(log_id: int) -> str:
    r = metrics.get_log(log_id)
    if not r:
        return _page("<div class='panel'><h2>未找到该日志</h2><p><a href='/logs'>返回列表</a></p></div>")
    state = "ok" if r["status"] == "ok" else "err"
    steps = "".join(
        f"<div>{i + 1}. <span class='tool'>{html.escape(t)}</span></div>" for i, t in enumerate(r["tool_sequence"])
    ) or '<span class="muted">未调用工具</span>'
    body = f"""
    <div class="panel">
      <h2>请求详情 #{r['id']}</h2>
      <div class="detail-row">
        <div class="detail-item"><div class="label">时间</div><div class="value">{html.escape(r['created_at'])}</div></div>
        <div class="detail-item"><div class="label">状态</div><div class="value {state}">{'成功' if r['status']=='ok' else '失败'}</div></div>
        <div class="detail-item"><div class="label">耗时</div><div class="value">{_fmt_ms(r['latency_ms'])}</div></div>
        <div class="detail-item"><div class="label">Token</div><div class="value">{r['total_tokens']}（prompt {r['prompt_tokens']} / completion {r['completion_tokens']}）</div></div>
        <div class="detail-item"><div class="label">上下文长度</div><div class="value">{r['context_len']} 字符</div></div>
        <div class="detail-item"><div class="label">请求 ID</div><div class="value muted">{html.escape(r['request_id'])}</div></div>
      </div>
      <h3 class="muted">问题</h3>
      <div class="qa">{html.escape(r['question'])}</div>
      <h3 class="muted">工具调用链</h3>
      {steps}
      <h3 class="muted">回答</h3>
      <div class="qa">{html.escape(r['answer']) or "<span class='muted'>（无回答）</span>"}</div>
      {"<div class='warn'>错误类型：" + html.escape(r['error_type']) + "</div>" if r['status'] != "ok" else ""}
      <p><a href="/logs">&lt;- 返回日志列表</a></p>
    </div>
    """
    return _page(body)


def render_health() -> str:
    from kairos.infrastructure.settings import PROJECT_ROOT

    try:
        from kairos.agent.runtime import NATIVE_TOOLS

        tool_count = len(NATIVE_TOOLS)
    except Exception:
        tool_count = "未知（未配置 DEEPSEEK_API_KEY 时无法加载）"
    rows = [
        ("模型", MODEL),
        ("注册工具数", str(tool_count)),
        ("Claude-Mem 长期记忆", "已配置" if CLAUDE_MEM_URL else "未配置（可选）"),
        ("SQLite 数据库", str(DB_PATH)),
        ("项目根目录", str(PROJECT_ROOT)),
        ("面板认证", "PANEL_TOKEN 已启用" if PANEL_TOKEN else "未设置 PANEL_TOKEN（仅建议本机使用）"),
        ("面板端口", str(PANEL_PORT)),
    ]
    rows_html = "".join(f"<tr><td>{html.escape(k)}</td><td>{html.escape(str(v))}</td></tr>" for k, v in rows)
    body = f"""
    <div class="panel"><h2>运行状态</h2><table>{rows_html}</table></div>
    <div class="panel"><h2>说明</h2><p class="muted">本面板为本地运维工具，数据来自请求日志（question/answer 已脱敏，owner 已哈希）。</p></div>
    """
    return _page(body)


def render_memories() -> str:
    stats = memory_store.count_memories()
    rows = memory_store.list_all_memories(limit=300)
    by_owner: dict[str, list[dict]] = {}
    for row in rows:
        by_owner.setdefault(row["owner_id"], []).append(row)
    cards = "".join(
        [
            _card("记忆总数", f"{stats['total']}", f"核心 {stats['core']} / 存档 {stats['archive']}"),
            _card("记忆用户", f"{stats['owners']}", "按用户隔离"),
        ]
    )
    if not rows:
        body = f"""
        {cards}
        <div class="panel"><h2>记忆列表</h2><p class="muted">还没有记忆。去飞书和助手聊天，助手会自动提取并保存长期记忆。</p></div>
        """
        return _page(body)
    sections = []
    for owner, owner_rows in by_owner.items():
        owner_rows.sort(key=lambda r: (not r["is_core"], r["updated_at"]), reverse=True)
        rows_html = ""
        for r in owner_rows:
            tag = "核心" if r["is_core"] else "存档"
            rows_html += (
                "<tr>"
                f"<td><span class='tag'>{tag}</span></td>"
                f"<td>{html.escape(r['category'])}</td>"
                f"<td>{html.escape(r['content'])}</td>"
                f"<td>{r['access_count']}</td>"
                f"<td class='muted'>{html.escape(r['updated_at'])}</td>"
                "<td><form method='post' action='/api/memories/delete' "
                f"onsubmit='return confirm(\"删除这条记忆？\")'>"
                f"<input type='hidden' name='memory_id' value='{html.escape(r['memory_id'])}'>"
                "<button class='btn' type='submit'>删除</button></form></td>"
                "</tr>"
            )
        sections.append(
            "<div class='panel'>"
            f"<h2>用户 {html.escape(owner)} <span class='muted'>({len(owner_rows)} 条)</span></h2>"
            "<table><tr><th>层级</th><th>类别</th><th>内容</th><th>访问</th><th>更新时间</th><th></th></tr>"
            f"{rows_html}</table>"
            f"<form method='post' action='/api/memories/clear' style='margin-top:8px' "
            f"onsubmit='return confirm(\"清空该用户全部记忆？\")'>"
            f"<input type='hidden' name='owner_id' value='{html.escape(owner)}'>"
            "<button class='btn' type='submit'>清空该用户记忆</button></form>"
            "</div>"
        )
    body = f"""
    <div class="cards">{cards}</div>
    {''.join(sections)}
    """
    return _page(body)


def render_graph() -> str:
    """Interactive force-directed knowledge graph view (self-contained, no CDN)."""
    body = """
    <style>
      .graph-toolbar { display:flex; gap:10px; align-items:center; margin-bottom:12px; flex-wrap:wrap; }
      .graph-toolbar input { padding:6px 10px; border:1px solid var(--border); border-radius:6px; font-size:13px; width:220px; }
      #graph-wrap { position:relative; height:72vh; border:1px solid var(--border); border-radius:10px; background:#fbfcfe; overflow:hidden; }
      #graph-canvas { width:100%; height:100%; display:block; cursor:grab; }
      #graph-canvas.dragging { cursor:grabbing; }
      #graph-empty { position:absolute; inset:0; display:none; align-items:center; justify-content:center; text-align:center; padding:20px; }
      .graph-legend { display:flex; gap:14px; flex-wrap:wrap; margin-top:10px; }
      .legend-item { display:inline-flex; align-items:center; gap:6px; font-size:12px; color:var(--muted); }
      .legend-dot { width:10px; height:10px; border-radius:50%; display:inline-block; }
      .graph-detail { margin-top:12px; padding:12px 14px; background:#fafbfc; border:1px solid var(--border); border-radius:8px; font-size:13px; min-height:20px; }
      .graph-detail .detail-title { font-size:14px; margin-bottom:8px; display:flex; align-items:center; gap:8px; flex-wrap:wrap; }
      .graph-detail .rel { padding:3px 0; border-bottom:1px dashed var(--border); }
      .graph-detail .rel .pred { color:var(--accent); font-weight:600; margin-right:6px; }
      #graph-tip { position:absolute; pointer-events:none; background:rgba(20,30,45,.92); color:#fff; padding:6px 10px; border-radius:6px; font-size:12px; display:none; z-index:5; }
    </style>
    <div class="cards">
      <div class="card"><div class="label">文档</div><div class="value" id="stat-docs">—</div></div>
      <div class="card"><div class="label">实体</div><div class="value" id="stat-entities">—</div></div>
      <div class="card"><div class="label">关系</div><div class="value" id="stat-relations">—</div></div>
    </div>
    <div class="panel">
      <div class="graph-toolbar">
        <input id="graph-search" placeholder="搜索实体并定位…">
        <button class="btn" id="graph-reset" type="button">重置视图</button>
        <span class="muted">滚轮缩放 · 拖拽平移 · 拖节点调整 · 点击查看关联</span>
      </div>
      <div id="graph-wrap">
        <canvas id="graph-canvas"></canvas>
        <div id="graph-tip"></div>
        <div id="graph-empty" class="warn"></div>
      </div>
      <div class="graph-legend" id="graph-legend"></div>
      <div class="graph-detail" id="graph-detail"><span class="muted">点击节点查看关联关系</span></div>
    </div>
    <script>
    (function(){
      function esc(s){ return String(s).replace(/[&<>"']/g, function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
      var canvas = document.getElementById('graph-canvas');
      var ctx = canvas.getContext('2d');
      var wrap = document.getElementById('graph-wrap');
      var tip = document.getElementById('graph-tip');
      var empty = document.getElementById('graph-empty');
      var detail = document.getElementById('graph-detail');
      var legendEl = document.getElementById('graph-legend');
      var dpr = window.devicePixelRatio || 1;

      function setStats(obj){
        document.getElementById('stat-docs').textContent = obj.documents;
        document.getElementById('stat-entities').textContent = obj.entities;
        document.getElementById('stat-relations').textContent = obj.relations;
      }

      fetch('/api/graph').then(function(r){ return r.json(); }).then(function(data){
        setStats(data.stats);
        var rawNodes = data.nodes || [];
        var rawEdges = data.edges || [];
        if (!rawNodes.length){
          empty.textContent = '知识图谱还是空的。去飞书让助手「把这份资料入库」，或通过 MCP 调用 knowledge_ingest，实体与关系就会出现在这里。';
          empty.style.display = 'flex';
          return;
        }
        init(rawNodes, rawEdges);
      }).catch(function(e){
        setStats({documents:'?', entities:'?', relations:'?'});
        empty.textContent = '加载图谱失败：/api/graph 不可用（' + esc(e && e.message ? e.message : '') + '）';
        empty.style.display = 'flex';
      });

      function init(rawNodes, rawEdges){
        var nodes = rawNodes.map(function(n){
          return { id: n.id, name: n.name, type: n.type, degree: n.degree || 0, x: 0, y: 0, vx: 0, vy: 0 };
        });
        var byId = {};
        nodes.forEach(function(n){ byId[n.id] = n; });
        var edges = [];
        rawEdges.forEach(function(e){
          var s = byId[e.source], t = byId[e.target];
          if (s && t) edges.push({ s: s, t: t, predicate: e.predicate });
        });
        var adj = {};
        nodes.forEach(function(n){ adj[n.id] = []; });
        edges.forEach(function(e){ adj[e.s.id].push(e); adj[e.t.id].push(e); });

        var palette = ['#1f77b4','#ff7f0e','#2ca02c','#d62728','#9467bd','#8c564b','#e377c2','#7f7f7f','#bcbd22','#17becf'];
        var typeColor = {};
        nodes.forEach(function(n){ if (!(n.type in typeColor)) typeColor[n.type] = palette[Object.keys(typeColor).length % palette.length]; });
        legendEl.innerHTML = Object.keys(typeColor).map(function(t){
          return '<span class="legend-item"><span class="legend-dot" style="background:' + typeColor[t] + '"></span>' + esc(t) + '</span>';
        }).join('');

        var W = 0, H = 0;
        function resize(){
          W = wrap.clientWidth; H = wrap.clientHeight;
          canvas.width = W * dpr; canvas.height = H * dpr;
          canvas.style.width = W + 'px'; canvas.style.height = H + 'px';
          render();
        }
        window.addEventListener('resize', resize);

        var margin = 60;
        nodes.forEach(function(n){
          n.x = margin + Math.random() * Math.max(1, W - 2 * margin);
          n.y = margin + Math.random() * Math.max(1, H - 2 * margin);
        });

        var view = { x: 0, y: 0, scale: 1 };
        var draggingNode = null, panning = false, hoverNode = null, moved = false;
        var lastX = 0, lastY = 0;

        function radius(n){ return Math.max(6, Math.min(22, 5 + Math.sqrt(n.degree) * 2.6)); }

        function step(){
          var k = 9000, rest = 110, gravity = 0.02, damp = 0.82, maxSpeed = 5;
          for (var i = 0; i < nodes.length; i++){
            var a = nodes[i];
            for (var j = i + 1; j < nodes.length; j++){
              var b = nodes[j];
              var dx = a.x - b.x, dy = a.y - b.y;
              var d2 = dx * dx + dy * dy + 1;
              var d = Math.sqrt(d2);
              var f = k / d2;
              a.vx += dx / d * f; a.vy += dy / d * f;
              b.vx -= dx / d * f; b.vy -= dy / d * f;
            }
          }
          edges.forEach(function(e){
            var dx = e.t.x - e.s.x, dy = e.t.y - e.s.y;
            var d = Math.sqrt(dx * dx + dy * dy) || 1;
            var f = (d - rest) * 0.006;
            e.s.vx += dx / d * f; e.s.vy += dy / d * f;
            e.t.vx -= dx / d * f; e.t.vy -= dy / d * f;
          });
          nodes.forEach(function(a){
            if (a === draggingNode) return;
            a.vx += (W / 2 - a.x) * gravity;
            a.vy += (H / 2 - a.y) * gravity;
            a.vx *= damp; a.vy *= damp;
            var sp = Math.sqrt(a.vx * a.vx + a.vy * a.vy);
            if (sp > maxSpeed){ a.vx *= maxSpeed / sp; a.vy *= maxSpeed / sp; }
            a.x += a.vx; a.y += a.vy;
          });
        }

        function worldPos(clientX, clientY){
          var rect = canvas.getBoundingClientRect();
          return { x: (clientX - rect.left - view.x) / view.scale, y: (clientY - rect.top - view.y) / view.scale };
        }

        function pickNode(wx, wy){
          for (var i = nodes.length - 1; i >= 0; i--){
            var n = nodes[i], r = radius(n) + 3;
            var dx = n.x - wx, dy = n.y - wy;
            if (dx * dx + dy * dy <= r * r) return n;
          }
          return null;
        }

        function render(){
          ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
          ctx.clearRect(0, 0, W, H);
          ctx.setTransform(dpr * view.scale, 0, 0, dpr * view.scale, dpr * view.x, dpr * view.y);
          edges.forEach(function(e){
            var dim = hoverNode && e.s !== hoverNode && e.t !== hoverNode;
            ctx.strokeStyle = dim ? 'rgba(180,190,200,.18)' : 'rgba(150,165,180,.55)';
            ctx.lineWidth = dim ? 0.6 : 1.1;
            ctx.beginPath(); ctx.moveTo(e.s.x, e.s.y); ctx.lineTo(e.t.x, e.t.y); ctx.stroke();
          });
          nodes.forEach(function(n){
            var r = radius(n);
            ctx.beginPath(); ctx.arc(n.x, n.y, r, 0, Math.PI * 2);
            ctx.fillStyle = typeColor[n.type] || '#999';
            ctx.fill();
            ctx.lineWidth = hoverNode === n ? 2.5 : 1;
            ctx.strokeStyle = hoverNode === n ? '#111' : 'rgba(0,0,0,.25)';
            ctx.stroke();
            ctx.fillStyle = '#222';
            ctx.font = (hoverNode === n ? 'bold ' : '') + '12px "Segoe UI","Microsoft YaHei",sans-serif';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'top';
            ctx.fillText(n.name, n.x, n.y + r + 3);
          });
        }

        var active = true;
        function frame(){
          if (active || draggingNode || panning){
            step();
            var maxV = 0;
            nodes.forEach(function(n){ var s = n.vx * n.vx + n.vy * n.vy; if (s > maxV) maxV = s; });
            active = maxV > 0.05;
          }
          render();
          requestAnimationFrame(frame);
        }

        function showTip(n, clientX, clientY){
          tip.innerHTML = '<b>' + esc(n.name) + '</b> · ' + esc(n.type) + ' · ' + n.degree + ' 条关系';
          tip.style.display = 'block';
          tip.style.left = (clientX - wrap.getBoundingClientRect().left + 14) + 'px';
          tip.style.top = (clientY - wrap.getBoundingClientRect().top + 14) + 'px';
        }
        function hideTip(){ tip.style.display = 'none'; }

        function showDetail(n){
          var html = '<div class="detail-title"><b>' + esc(n.name) + '</b> <span class="tag">' + esc(n.type) + '</span> <span class="muted">' + n.degree + ' 条关系</span></div>';
          var rels = adj[n.id].map(function(e){
            if (e.s.id === n.id) return '<div class="rel"><span class="pred">' + esc(e.predicate) + '</span>→ ' + esc(e.t.name) + '</div>';
            return '<div class="rel">' + esc(e.s.name) + ' <span class="pred">' + esc(e.predicate) + '</span>→ 当前实体</div>';
          });
          detail.innerHTML = html + (rels.join('') || '<div class="muted">无关联关系</div>');
        }

        canvas.addEventListener('mousedown', function(ev){
          moved = false;
          var wp = worldPos(ev.clientX, ev.clientY);
          var n = pickNode(wp.x, wp.y);
          if (n) draggingNode = n; else panning = true;
          lastX = ev.clientX; lastY = ev.clientY;
          canvas.classList.add('dragging');
          ev.preventDefault();
        });
        window.addEventListener('mousemove', function(ev){
          if (draggingNode){
            var wp = worldPos(ev.clientX, ev.clientY);
            draggingNode.x = wp.x; draggingNode.y = wp.y;
            draggingNode.vx = 0; draggingNode.vy = 0;
            if (Math.abs(ev.clientX - lastX) + Math.abs(ev.clientY - lastY) > 2) moved = true;
            lastX = ev.clientX; lastY = ev.clientY;
            return;
          }
          if (panning){
            view.x += ev.clientX - lastX; view.y += ev.clientY - lastY;
            if (Math.abs(ev.clientX - lastX) + Math.abs(ev.clientY - lastY) > 2) moved = true;
            lastX = ev.clientX; lastY = ev.clientY;
            render();
            return;
          }
          var wp = worldPos(ev.clientX, ev.clientY);
          var n = pickNode(wp.x, wp.y);
          if (n !== hoverNode){ hoverNode = n; render(); }
          if (n) showTip(n, ev.clientX, ev.clientY); else hideTip();
        });
        window.addEventListener('mouseup', function(){
          draggingNode = null; panning = false;
          canvas.classList.remove('dragging');
        });
        canvas.addEventListener('click', function(ev){
          if (moved) return;
          var wp = worldPos(ev.clientX, ev.clientY);
          var n = pickNode(wp.x, wp.y);
          if (n) showDetail(n);
        });
        canvas.addEventListener('wheel', function(ev){
          ev.preventDefault();
          var factor = ev.deltaY < 0 ? 1.12 : 1 / 1.12;
          var rect = canvas.getBoundingClientRect();
          var mx = ev.clientX - rect.left, my = ev.clientY - rect.top;
          var newScale = Math.max(0.15, Math.min(6, view.scale * factor));
          var k = newScale / view.scale;
          view.x = mx - (mx - view.x) * k;
          view.y = my - (my - view.y) * k;
          view.scale = newScale;
          render();
        }, { passive: false });

        document.getElementById('graph-reset').addEventListener('click', function(){
          view.x = 0; view.y = 0; view.scale = 1; hoverNode = null; render();
        });
        document.getElementById('graph-search').addEventListener('input', function(ev){
          var q = (ev.target.value || '').trim().toLowerCase();
          if (!q){ hoverNode = null; render(); return; }
          var hit = null;
          nodes.forEach(function(n){ if (!hit && n.name.toLowerCase().indexOf(q) !== -1) hit = n; });
          if (hit){
            view.x = W / 2 - hit.x * view.scale;
            view.y = H / 2 - hit.y * view.scale;
            hoverNode = hit;
            render();
            showDetail(hit);
          }
        });

        resize();
        requestAnimationFrame(frame);
      }
    })();
    </script>
    """
    return _page(body)


def create_app() -> Flask:
    app = Flask(__name__)
    app.json.ensure_ascii = False

    @app.before_request
    def require_token() -> Any:
        if not _auth_ok():
            return jsonify({"error": "unauthorized", "hint": "set PANEL_TOKEN or pass ?token="}), 401
        return None

    @app.get("/")
    def dashboard() -> str:
        return render_dashboard()

    @app.get("/logs")
    def logs() -> str:
        return render_logs()

    @app.get("/logs/<int:log_id>")
    def log_detail(log_id: int) -> str:
        return render_log_detail(log_id)

    @app.get("/health")
    def health() -> str:
        return render_health()

    @app.get("/memories")
    def memories() -> str:
        return render_memories()

    @app.get("/graph")
    def graph() -> str:
        return render_graph()

    @app.get("/api/graph")
    def api_graph() -> Any:
        try:
            kg_engine.init()
            return jsonify(kg_engine.export_graph())
        except Exception as exc:  # noqa: BLE001
            return jsonify({"error": str(exc)}), 500

    @app.post("/api/memories/delete")
    def api_memory_delete() -> Any:
        memory_id = request.form.get("memory_id", "")
        if memory_id and memory_store.delete_memory(memory_id):
            return redirect("/memories")
        return "未找到该记忆", 404

    @app.post("/api/memories/clear")
    def api_memory_clear() -> Any:
        owner_id = request.form.get("owner_id", "")
        if owner_id:
            memory_store.forget_memories(owner_id)
        return redirect("/memories")

    @app.get("/api/summary")
    def api_summary() -> Any:
        return jsonify(metrics.summary())

    @app.get("/api/logs")
    def api_logs() -> Any:
        page = max(1, int(request.args.get("page", "1") or 1))
        status = request.args.get("status", "")
        tool = request.args.get("tool", "").strip()
        rows, total = metrics.list_logs(page=page, status=status, tool=tool)
        return jsonify({"total": total, "page": page, "rows": rows})

    @app.get("/api/logs/<int:log_id>")
    def api_log_detail(log_id: int) -> Any:
        row = metrics.get_log(log_id)
        return (jsonify(row), 200) if row else (jsonify({"error": "not found"}), 404)

    @app.get("/api/tools")
    def api_tools() -> Any:
        return jsonify(metrics.tool_stats())

    return app


def main() -> None:
    metrics.init_metrics_table()
    memory_store.init_db()
    app = create_app()
    print(f"web panel listening on {PANEL_HOST}:{PANEL_PORT}" + (" (PANEL_TOKEN required)" if PANEL_TOKEN else ""))
    app.run(host=PANEL_HOST, port=PANEL_PORT, debug=False, use_reloader=False)


if __name__ == "__main__":
    main()
